# List of parameters with VCFfile path, output folder path and the list of filters to apply with their parameters in
# a YAML file. The filters are applied in the order they are listed in the YAML file. The filters are applied to the
# VCF file.

# Specify the path to the VCF file and the output folder path for the filtered VCF files
vcf_file_path: "variantsfile_Annotated.vcf"
output_folder_path: "vcf_filtered"

# Specify the columns names for the superior parental, inferior parental, superior pool and random pool in the VCF file
parental_sup_column: "Samplen206_"
parental_inf_column: "Samplen205_"
pool_sup_column: "Samplen207_"
pool_rnd_column: "Samplen208_"

# List of filters to apply to the VCF file
filters:

  - name: "at_least"
    n_reads: "1"
    Description: >
      Filter condition: check if the superior parental allele nucleotide count is greater than or equal to the 
      specified number in the superior pool nucleotide count


  - name: "percent_threshold"
    threshold: "75"
    Description: >
      Filter out variants that do not have the reference allele count greater than the specified percentage of the total allele count

  - name: "parental_sup_greater"
    Description: >
      Filter condition: check if the superior parental allele frequency is greater than the other nucleotides 
      frequency in the superior pool nucleotide count frequency

  # Accept variants that have the superior parental allele on superior pool frequency closer to the greatest frequency
  - name: "diff_from_greater"
    diff_max: "10"
    
  # Verify if random pool allele equal to superior parental has a mean percentage is between the average and standard deviation
  - name: "rnd_mean"
    threshold: "75"
    avg_count : "50"
    std_dev : "2"